- name: Build and Push Docker Image
      run: |
        cd MLProject
        RUN_ID=$(cat run_id.txt)
        
        # 1. Suruh MLflow membuat folder dan Dockerfile-nya (jangan langsung dibuild)
        mlflow models generate-dockerfile -m "runs:/$RUN_ID/model" -d docker_build_dir
        
        # 2. Gunakan trik Linux 'sed' untuk mengganti URL sesuai saran Copilot
        sed -i 's|https://bootstrap.pypa.io/get-pip.py|https://bootstrap.pypa.io/pip/3.9/get-pip.py|g' docker_build_dir/Dockerfile
        
        # 3. Build image secara manual dari folder yang sudah diperbaiki
        docker build -t "${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest" docker_build_dir/
        
        # 4. Push ke Docker Hub
        docker push "${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest"